# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    #command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: teste
      MYSQL_DATABASE: DeliciasCaseiras
    #ports:
    #- 3306:3306
    #volumes:
    #- d:\data:/var/lib/mysql


  